"""
Django settings for promesak project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = ['aginduak.eibar.org', '127.0.0.1']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'tinymce',
    'compressor',
    'promesak',
    'promesak.base',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'promesak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'promesak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

TINYMCE_BODY_CONFIG = {
    "mode": "exact",
    "elements": "content",
    "extended_valid_elements": "iframe[src|name|width|height|align|frameborder|marginwidth|marginheight|scrolling|table]",
    "theme": "advanced",
    "theme_advanced_buttons1": "styleselect,bold,italic,underline,separator,bullist,numlist,undo,redo,link,unlink,image,code,removeformat,cut,copy,paste,pastetext,pasteword,selectall,pastetext,table",
    "theme_advanced_buttons2": "",
    "theme_advanced_buttons3": "",
    "theme_advanced_toolbar_location": "top",
    "theme_advanced_toolbar_align": "left",
    "plugins": "paste,table",
    "tools": "inserttable",
    "paste_auto_cleanup_on_paste": "true",
    "paste_use_dialog": "false",
    "forced_root_block": "p",
    "convert_urls": "false",
    "extended_valid_elements":"object[width|height|classid|codebase],param[name|value],embed[src|type|width|height|flashvars|wmode]",
    "style_formats": [
        {"title" : "Subtitulo h2", "block" : 'h2'},
        {"title" : "Subtitulo h3", "block" : 'h3'},
        {"title" : "Subtitulo h4", "block" : 'h4'},
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'eu'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

DEBUG = False


try:
    from server_settings import *
except ImportError:
    # Create a server_settings.py file in a folder called conf
    # one level above the buildout directory and fill the production
    # server details
    SECRET_KEY = ''

    STATIC_ROOT = '/tmp/static'
    MEDIA_ROOT = '/tmp/media'


    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': '',
            'USER': '',
            'PASSWORD': '',
            'HOST': '',

        }
    }
